### ISSUE TITLE
Feature Request: Reuse same Finder window

### ISSUE THREAD

**Issue by byalextran** [Acidham/recent-files-in-folders#1]
thanks for this workflow! it's been a big help since discovering it. 

if possible, one thing i'd love is the option to reuse finder windows. that way if i use the workflow to go to a file in a folder, instead of opening a new folder it would reuse an existing finder window. 

i could see a couple different approaches:

1. if a finder window is currently open to the same folder, re-use that one. 
2. if a finder window is not open to the same folder, open a new window. 
3. instead of opening a new window, re-use an existing window and open a new tab in it. 

all in all, my goal is to avoid having 10 finder windows open to the same folder.

**Comment by Acidham** [comment]
@byalextran nice to hear that the WF is useful ;)

I mainly rely on default file actions (pressing TAB). If you prefer to use some finder logic it needs to be implemented as custom file action but this is not part of "recent-files-in-folders".
