### ISSUE TITLE
Option to return results from subfolders?

### ISSUE THREAD

**Issue by bumpux** [Acidham/recent-files-in-folders#2]
Love this. Wondering it you've considered letting it drill down inside subfolders. So if I have:

Folder Foo
    ⇥ Folder Bar
    ⇥ Folder Baz

where Bar and Baz contain files with names matching `string-one`, the extension returns a list:

 - this-string-one.pdf (Baz)
 - that-string-one.md (Bar)

ordered by last modified, of course

Config could be a checkbox [ ] "Search subfolders"

If I were clever enough I would dig into code :-) I assume this is not trivial but perhaps a feature you've considered. Limiting depth to one or two levels might be necessary. Thanks in any case for a great utility.

**Comment by Acidham** [comment]
Done...
