### ISSUE TITLE
Is it possible to use several folder destinations for searching recent files? 

### ISSUE THREAD

**Issue by maxim-uvarov** [Acidham/recent-files-in-folders#3]
Hi there:) 
I wonder if it is possible to use several folders with one argument name? 
I used new line and comma, semicolon as delimiters, and it didn't work ![](https://www.screencast.com/t/Tu4v1nTTw)

**Comment by Acidham** [comment]
Which version of the WF are you using?

**Comment by maxim-uvarov** [comment]
v3.3.2

**Comment by maxim-uvarov** [comment]
I've just updated to the latest one, and so I can update my question: Can I search for recent files in several folders with one query?

**Comment by Acidham** [comment]
No, the workflow was built to get list of recent files in a folder. Searching across all folder is not planned due to different use case, sry.
