### ISSUE TITLE
Is it possible to add the shortcut or keyword for the specific folder? 

### ISSUE THREAD

**Issue by maxim-uvarov** [Acidham/recent-files-in-folders#5]
Thanks for the convenient workflow! I wonder if adding the shortcut or keyword for the specific folder is possible? Without the intermediate step of choosing a folder?

**Comment by Acidham** [comment]
Sure, you can add keyboard shortcut with the path as argument before the first "arg and vars" step. important is to submit absolute path as text

**Comment by maxim-uvarov** [comment]
Thanks a lot!
